project:
  type: website
  output-dir: docs

website:
  title: "Matthew Trevino's ePortfolio"
  navbar: Chess_proj_final.qmd
    left:
      - href: index2.qmd
        text: 
      - href: about2.qmd
        text: 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
